### ISSUE TITLE
instance fields have getters by default

### ISSUE THREAD

**Issue by dragoncoder047** [agate-lang/agate#1]
https://github.com/agate-lang/agate/blob/9a2f4fc042d62109be461a830f4439779ae64d37/examples/logo.agate#L166-L168

Making instance fields have these style of getters by default would eliminate these kinds of lines.

To allow the getters to *not* automatically be added you could define some sort of naming rule for "private" fields -- Python uses `__name`.

does this sound like a good idea?

**Comment by jube** [comment]
> does this sound like a good idea?

It's not a good or a bad idea, it's a design choice. I prefer the current state for the following reason: encapsulation is stronger and if you want to expose a field, you have to opt in and write a getter. Making all fields public by default would be exactly the contrary, you would have to propose something to opt out (naming rule, keyword or something else).

At one point, I thought about introducing something like `attr_reader`/`attr_writer`/`attr_accessor` from Ruby. But in the end, writing `x { @x }` is shorter and more explicit than `attr_reader x`.

**Comment by dragoncoder047** [comment]
Okay, then. Never mind...
